export const FONT_OPTIONS = [
  // Sans-serif
  "Inter",
  "Roboto",
  "Poppins",
  "Montserrat",
  "Lato",
  "Open Sans",
  "Nunito",
  "Raleway",
  "Oswald",
  "Quicksand",
  "Work Sans",
  "Source Sans 3",
  "DM Sans",
  "Manrope",
  "Rubik",
  "Karla",
  "Josefin Sans",
  "Ubuntu",
  "Mukta",
  "Outfit",
  "Space Grotesk",
  "Plus Jakarta Sans",
  "Archivo",
  "Comfortaa",
  "Nunito Sans",
  "Noto Sans",
  "IBM Plex Sans",
  "Barlow",
  "Cabin",
  "Titillium Web",
  "Mulish",
  "Red Hat Display",
  "Sora",
  "Be Vietnam Pro",
  "Lexend",
  "Figtree",
  "Exo 2",
  "Varela Round",
  "Hind",
  "Fjalla One",
  "Libre Franklin",
  "Baloo 2",
  "Jost",
  // Serif
  "Playfair Display",
  "Merriweather",
  "Lora",
  "PT Serif",
  "Fraunces",
  "Cormorant Garamond",
  "Libre Baskerville",
  "Crimson Text",
  "EB Garamond",
  "Bitter",
  "Zilla Slab",
  "Spectral",
  "Noto Serif",
  "IBM Plex Serif",
  "Alegreya",
  "Vollkorn",
  "Cardo",
  "Libre Caslon Text",
  "Domine",
  "Cinzel",
  "Philosopher",
  "Neuton",
  "Alfa Slab One",
  "Arvo",
  "Literata",
  // Display
  "Abril Fatface",
  "Bebas Neue",
  "Anton",
  "Righteous",
  "Russo One",
  "Lobster Two",
  "Black Ops One",
  "Permanent Marker",
  "Acme",
  "Secular One",
  "Graduate",
  // Script / Manuscrites
  "Caveat",
  "Pacifico",
  "Dancing Script",
  "Beth Ellen",
  "Great Vibes",
  "Satisfy",
  "Sacramento",
  "Allura",
  "Pinyon Script",
  "Lobster",
  "Kalam",
  "Patrick Hand",
  "Indie Flower",
  "Shadows Into Light",
  "Yellowtail",
  // Monospace
  "JetBrains Mono",
  "Source Code Pro",
  "Fira Code",
  "Roboto Mono",
  "IBM Plex Mono",
  "Space Mono",
];
