export const FONT_OPTIONS = [
  "Inter",
  "Roboto",
  "Poppins",
  "Montserrat",
  "Lato",
  "Open Sans",
  "Nunito",
  "Raleway",
  "Playfair Display",
  "Merriweather",
  "Oswald",
  "Quicksand",
  "Work Sans",
  "Source Sans 3",
  "DM Sans",
  "Manrope",
  "Lora",
  "PT Serif",
  "Rubik",
  "Karla",
  "Fraunces",
  "Cormorant Garamond",
  "Josefin Sans",
  "Ubuntu",
  "Mukta",
  "Outfit",
  "Space Grotesk",
  "Plus Jakarta Sans",
  "Libre Baskerville",
  "Crimson Text",
  "EB Garamond",
  "Caveat",
  "Pacifico",
  "Dancing Script",
  "Abril Fatface",
  "Bitter",
  "Archivo",
  "Comfortaa",
  "Nunito Sans",
  "Zilla Slab",
];
